#Copied from mhttps://github.com/tobru/nextcloud-openshift/blob/master/nextcloud.yaml
apiVersion: v1
kind: Template
metadata:
  name: nextcloud-apache
  annotations:
    description: "Nextcloud - A safe home for all your data"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "tobrunet"
    template.openshift.io/documentation-url: "https://github.com/tobru/nextcloud-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/tobru/nextcloud-openshift/issues"
parameters:
- name: NEXTCLOUD_HOST
  description: Application URL of Nextcloud (Route/host)
  required: true
- name: PVC_SIZE
  description: PVC size for Apps, Config and Data
  value: 5Gi
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nextcloud-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${PVC_SIZE}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nextcloud
    name: nextcloud
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: nextcloud
    name: nextcloud
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'nextcloud:latest'
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 2
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    replicas: 1
    selector:
      app: nextcloud
      deploymentconfig: nextcloud
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: nextcloud
          deploymentconfig: nextcloud
      spec:
        containers:
        - env:
          - name: NC_dbhost
            value: mariadb
          - name: NC_dbuser
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mariadb
          - name: NC_dbpassword
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mariadb
          - name: NC_dbname
            value: nextcloud
          image: nextcloud
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          name: nextcloud
          ports:
          - containerPort: 9000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/www/html
            name: nextcloud-source
          - mountPath: /var/www/html/data
            name: nextcloud-data
            subPath: data
          - mountPath: /var/www/html/config
            name: nextcloud-data
            subPath: config
          - mountPath: /var/www/html/custom_apps
            name: nextcloud-data
            subPath: apps
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: nextcloud-source
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - nextcloud
        from:
          kind: ImageStreamTag
          name: nextcloud:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nextcloud
      deploymentconfig: nextcloud
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: nextcloud
  spec:
    host: ${NEXTCLOUD_HOST}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: nextcloud
      weight: 100
    wildcardPolicy: None
