apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: graylog
    deploymentconfig: graylog
  type: ClusterIP