apiVersion: v1
kind: BuildConfig
metadata:
  name: graylog-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'graylog:3.0-OKD'
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: "GRAYLOG_VERSION"
          value: "3.0.0-beta.4"
